/**
 * Lista oficial das 96 escolas municipais de Betim - SAIN
 * Fonte: Secretaria Municipal de Educação de Betim
 */
export const BETIM_SCHOOLS = [
  "CIM Alessandro Ferreira de Souza",
  "CIM Antônio Bernardes (Icaivera)",
  "CIM Antônio Honório da Silva",
  "CIM Cantinho do Beija-Flor",
  "CIM Castorina Moreira de Jesus - Dona Nina",
  "CIM Conceição Guilhermina da Silva",
  "CIM Criança Esperança",
  "CIM Dom Bosco",
  "CIM Dona Marta de Jesus",
  "CIM Emanuel Marcelino Maia Silva",
  "CIM Emílio Mafia Gomes",
  "CIM Enis de Souza Soares",
  "CIM Geraldo Jorge Meira",
  "CIM José Alves Pinto",
  "CIM Maria Engrácia de Souza",
  "CIM Recanto Alvorada",
  "CIM Pequeno Príncipe",
  "CIM Rafaela Santana Assis",
  "CIM Recanto da Criança",
  "CIM Santo Paschoalin",
  "CIM São Luiz",
  "CIM Sementes do Amanhã",
  "CIM Silvana Rodrigues Silva Pedrosa",
  "CIM Paulo Monteiro Lara",
  "CIM Sônia Maria Ferreira",
  "CIM Tia Dulce",
  "CIM Wilma da Costa Pinto Afonso",
  "Centro Educacional Técnico e de Artes Profissionais",
  "E M Abílio Gomes da Costa",
  "E M Adelina Gonçalves Campos",
  "E M Adelina Mesquita Januzzi",
  "E M Alair Ferreira de Souza",
  "E M Alice Pinheiro Araújo",
  "E M Ana Cândida de Jesus",
  "E M Ângela Ribeiro Batista Maia",
  "E M Antônio D'Assis Martins",
  "E M Antônio Honório da Silva",
  "E M Antônio Tereza dos Santos",
  "E M Aristides José da Silva",
  "E M Arthur Trindade",
  "E M Barão do Rio Branco",
  "E M Belizário Ferreira Caminhas",
  "E M Bento Machado Ribeiro",
  "E M Carmelita Catarina da Mata",
  "E M Clóvis Salgado",
  "E M Desembargador Souza Lima",
  "E M do Bairro São Cristovão",
  "E M Edir Terezinha de Almeida Fagundes",
  "E M Edméia Duarte de Oliveira Braga",
  "E M Edvaldo Faleiro de Aguiar",
  "E M Fausto Figueiredo de Oliveira",
  "E M Florestan Fernandes",
  "E M Francisco de Sales Barbosa",
  "E M Frei Edgard Groot",
  "E M Frei Rogato",
  "E M Geferson Ventura de Souza",
  "E M Geraldo Jorge Meira",
  "E M Gilberto Alves da Silva",
  "E M Gino José de Souza",
  "E M Isaura Coelho",
  "E M Israel José Carlos",
  "E M João Batista Machado de Brito",
  "E M Jorge Afonso Defensor",
  "E M José Miranda Sobrinho",
  "E M José Nogueira Duarte",
  "E M José Salustiano Lara",
  "E M José Vilaça Guimarães",
  "E M Josefina Macedo Gontijo",
  "E M Lúcia Farage de Freitas Gumiero",
  "E M Manoel Saturnino de Carvalho",
  "E M Marcílio Melo Rezende",
  "E M Margarida Soares Guimarães",
  "E M Maria Aracélia Alves",
  "E M Maria Cristina",
  "E M Maria da Conceição Brito",
  "E M Maria da Penha dos Santos Almeida",
  "E M Maria de Lourdes Oliveira",
  "E M Maria Elena da Cunha Braz",
  "E M Maria José Campos",
  "E M Maria Mourici Granieri",
  "E M Mario Marcos Cordeiro Tupynambá",
  "E M Olímpia Maria da Glória",
  "E M Osório Aleixo da Silva",
  "E M Paulo Monteiro Lara",
  "E M Prefeito Alcides Braz",
  "E M Presidente Raul Soares",
  "E M Professor Kássio Vinícius Castro Gomes",
  "E M Raul Saraiva Ribeiro",
  "E M Rita Maria Silva - Tia Ritinha",
  "E M Sebastiana Diniz Matos Cardoso",
  "E M Sebastião Ferreira de Oliveira",
  "E M Tito Flávius Lima Andrade",
  "E M Valério Ferreira Palhares",
  "E M Vereador Rafael Barbizan",
  "E M Waldemar D'Luz Gonçalves",
  "E M Silvio Lobo",
] as const;

export type BetimSchool = typeof BETIM_SCHOOLS[number];

// Separação por tipo para os rankings do dashboard
export const EM_SCHOOLS = BETIM_SCHOOLS.filter(s => s.startsWith("E M"));
export const CIM_SCHOOLS = BETIM_SCHOOLS.filter(s => s.startsWith("CIM"));

// Tipos de deficiência para o dashboard
export const DISABILITY_TYPES = [
  "Autismo (TEA)",
  "Deficiência Intelectual",
  "Deficiência Física",
  "Deficiência Visual",
  "Deficiência Auditiva",
  "Deficiência Múltipla",
  "Síndrome de Down",
  "TDAH",
  "Transtorno de Aprendizagem",
  "Outro",
] as const;

// Motivos de inatividade
export const INACTIVITY_REASONS = [
  "Licença médica",
  "Licença maternidade/paternidade",
  "Afastamento por acidente de trabalho",
  "Férias",
  "Suspensão",
  "Demissão",
  "Aposentadoria",
  "Transferência de escola",
  "Vaga em aberto",
  "Outro",
] as const;
